// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL4E5Zn9ZPgFCmQrpzdrrB5yHcgevN9_k',
    appId: '1:659685709903:web:60c4cd8b202c79eedc723a',
    messagingSenderId: '659685709903',
    projectId: 'employee-management-app-e81ab',
    authDomain: 'employee-management-app-e81ab.firebaseapp.com',
    storageBucket: 'employee-management-app-e81ab.firebasestorage.app',
    measurementId: 'G-MWSBD165BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbUKnRLfN_XNFGyNySB3V38VKr4eFEiUw',
    appId: '1:659685709903:android:1342e3eb32b948a6dc723a',
    messagingSenderId: '659685709903',
    projectId: 'employee-management-app-e81ab',
    storageBucket: 'employee-management-app-e81ab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL4E5Zn9ZPgFCmQrpzdrrB5yHcgevN9_k',
    appId: '1:659685709903:web:8fc84908b6649e7fdc723a',
    messagingSenderId: '659685709903',
    projectId: 'employee-management-app-e81ab',
    authDomain: 'employee-management-app-e81ab.firebaseapp.com',
    storageBucket: 'employee-management-app-e81ab.firebasestorage.app',
    measurementId: 'G-2MT0W1LBP7',
  );
}
